addons:
  apt:
    packages:
      - python-pygments

script:
  - mkdir public
  - chmod 770 ./binaries/hugo
  - ./binaries/hugo
  - cp google4a768c937c82c1de.html public

deploy:
  provider: pages
  target-branch: master
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN
  on:
    branch: hugo
