# Install the apt prerequisites
addons:
  apt:
    packages:
      - python-pygments

# Build the website
script:
  - mkdir public
  - chmod 770 ./binaries/hugo
  - ./binaries/hugo
  - cp google4a768c937c82c1de.html public
# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
